
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pared
 */
public class Frame3 extends javax.swing.JFrame {

    /**
     * Creates new form Frame3
     */
    double v [];
    double v2[];
    double r[];
    private int k;
    public Frame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmbCrear = new javax.swing.JButton();
        cmbLlenadoManual = new javax.swing.JButton();
        cmbLlenadoAutom = new javax.swing.JButton();
        cmbMostrar = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        cmbSuma = new javax.swing.JButton();
        cmbResta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultadoVector1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultadoVector2 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtVectorResultante = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Vectores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Longitud de Vectores:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });
        jPanel2.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCrear.setText("Crear");
        cmbCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmbCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        cmbLlenadoManual.setText("Llenado Manual");
        cmbLlenadoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLlenadoManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmbLlenadoManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));

        cmbLlenadoAutom.setText("Llenado Autom");
        cmbLlenadoAutom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLlenadoAutomActionPerformed(evt);
            }
        });
        jPanel3.add(cmbLlenadoAutom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        cmbMostrar.setText("Mostrar");
        cmbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmbMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 110, 110, -1));

        cmbBorrar.setText("Borrar");
        cmbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, -1));

        cmbSuma.setText("Suma");
        cmbSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSumaActionPerformed(evt);
            }
        });
        jPanel3.add(cmbSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, -1));

        cmbResta.setText("Resta");
        cmbResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRestaActionPerformed(evt);
            }
        });
        jPanel3.add(cmbResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 150, 240));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vector1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultadoVector1.setEditable(false);
        txtResultadoVector1.setColumns(20);
        txtResultadoVector1.setRows(5);
        jScrollPane1.setViewportView(txtResultadoVector1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 130));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 160));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vector 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultadoVector2.setEditable(false);
        txtResultadoVector2.setColumns(20);
        txtResultadoVector2.setRows(5);
        jScrollPane2.setViewportView(txtResultadoVector2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 130));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 160));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vector Resultante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVectorResultante.setEditable(false);
        txtVectorResultante.setColumns(20);
        txtVectorResultante.setRows(5);
        jScrollPane3.setViewportView(txtVectorResultante);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 130));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 190, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCrearActionPerformed
        // TODO add your handling code here:
        int longitud;
        if (txtLongitud.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese la Longitud", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else if(Integer.parseInt(txtLongitud.getText().trim())==0)
        {
            JOptionPane.showMessageDialog(this, "La Longitud no puede ser cero", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
            txtLongitud.selectAll();
        }
        else {
        longitud = Integer.parseInt(txtLongitud.getText().trim());
        v= new double [longitud];
        v2= new double [longitud];
        r= new double [longitud];
        JOptionPane.showMessageDialog(this, "Vectores creados Correctamente");
        }
    }//GEN-LAST:event_cmbCrearActionPerformed

    private void cmbLlenadoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLlenadoManualActionPerformed
        // TODO add your handling code here:
        double n;
        double y;
        for (int i = 0; i < v.length; i++) 
        {
           n= Double.parseDouble(JOptionPane.showInputDialog(this, "Ingrese los numeros Vector 1"));
            v[i]=n;
        }
        for (int j = 0; j < v.length; j++) 
        {
            y= Double.parseDouble(JOptionPane.showInputDialog(this,"Ingrese los numeros Vector 2 "));
            v2[j]=y;        
        }
    }//GEN-LAST:event_cmbLlenadoManualActionPerformed

    private void cmbLlenadoAutomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLlenadoAutomActionPerformed
        // TODO add your handling code here:
        double n;
        double y;
        
        for (int i = 0; i < v.length; i++) 
        {
            n= (int)(Math.random()* 50 + 1);
            v[i]=n;
        }
        for (int j = 0; j < v.length; j++) 
        {
            y= (int)(Math.random()* 50 + 1);
            v2[j]=y; 
        }
    }//GEN-LAST:event_cmbLlenadoAutomActionPerformed

    private void cmbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMostrarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < v.length; i++) 
        {
            txtResultadoVector1.append(v[i]+"\n");
        }
        for (int j = 0; j < v.length; j++) 
        {
            txtResultadoVector2.append(v2[j]+"\n");
        }
    }//GEN-LAST:event_cmbMostrarActionPerformed

    private void cmbSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSumaActionPerformed
        // TODO add your handling code here
        for (int i = 0; i < v.length; i++) 
        {   
            r[i]=  v[i] + v2[i];
       txtVectorResultante.append("La suma es:"+r[i]+"\n");
        }
    }//GEN-LAST:event_cmbSumaActionPerformed

    private void cmbRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRestaActionPerformed
        // TODO add your handling code here:
        double d=0;
        for (int i = 0; i < v.length; i++) 
        {   
            r[i]=  v[i] - v2[i];
         txtVectorResultante.append("La resta es:"+r[i]+"\n");

        }
    }//GEN-LAST:event_cmbRestaActionPerformed

    private void cmbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarActionPerformed
        // TODO add your handling code here:
        txtResultadoVector1.setText("");
        txtLongitud.setText("");
        txtResultadoVector2.setText("");
        txtVectorResultante.setText("");
        txtLongitud.requestFocusInWindow();
        
        v=null;
        r=null;
        v2=null;
    }//GEN-LAST:event_cmbBorrarActionPerformed

    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          } 
    }//GEN-LAST:event_txtLongitudKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbCrear;
    private javax.swing.JButton cmbLlenadoAutom;
    private javax.swing.JButton cmbLlenadoManual;
    private javax.swing.JButton cmbMostrar;
    private javax.swing.JButton cmbResta;
    private javax.swing.JButton cmbSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextArea txtResultadoVector1;
    private javax.swing.JTextArea txtResultadoVector2;
    private javax.swing.JTextArea txtVectorResultante;
    // End of variables declaration//GEN-END:variables
}
